# Generated by Django 3.2.5 on 2021-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('linkedln', models.URLField(max_length=30, unique=True)),
                ('github', models.URLField(max_length=30, unique=True)),
                ('insta', models.URLField(max_length=30, unique=True)),
                ('skill1', models.CharField(max_length=30)),
                ('skill2', models.CharField(max_length=30)),
                ('skill3', models.CharField(max_length=30)),
                ('skill4', models.CharField(max_length=30)),
                ('objective', models.TextField(max_length=200)),
                ('work1', models.TextField(max_length=50)),
                ('work2', models.TextField(max_length=50)),
                ('edu1', models.TextField(max_length=50)),
                ('edu2', models.TextField(max_length=50)),
                ('ih1', models.TextField(max_length=50)),
                ('ih2', models.TextField(max_length=50)),
                ('ref', models.TextField(max_length=50)),
            ],
        ),
    ]
