# Generated by Django 3.2.5 on 2021-07-28 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(default='gmail.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.IntegerField(default='9561384299', unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu1',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu2',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='Navi Mumbai', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.URLField(default='github.com', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ih1',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ih2',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='insta',
            field=models.URLField(default='instagram.com', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedln',
            field=models.URLField(default='linkedin.com', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='Rohan', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='objective',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ref',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill1',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill2',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill3',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill4',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work1',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work2',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
