# Generated by Django 3.2.5 on 2021-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210728_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.URLField(default='github.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='https://p.kindpng.com/picc/s/153-1530388_mario-head-png-png-download-people-profile-pic.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='insta',
            field=models.URLField(default='instagram.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedln',
            field=models.URLField(default='linkedin.com', max_length=30),
        ),
    ]
