# Generated by Django 3.2.5 on 2021-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210729_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(default='gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='Navi Mumbai', max_length=30),
        ),
    ]
