# Generated by Django 3.2.5 on 2021-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210729_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.IntegerField(default='9561384299'),
        ),
    ]
