# Generated by Django 3.2.5 on 2021-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='https://p.kindpng.com/picc/s/153-1530388_mario-head-png-png-download-people-profile-pic.png', upload_to='media'),
        ),
    ]
