# Generated by Django 3.2.5 on 2021-07-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='myapp_image',
        ),
    ]
